// Package layout provides helpers for working with keys layout
package layout

import "github.com/mishamyrt/nuga-lib/device"

// Template represents keyboard layout template
type Template map[KeyName]uint32

// GetPosition returns key position
func (l Template) GetPosition(key KeyName) uint32 {
	return l[key]
}

// GetKey returns key name by position
func (l Template) GetKey(position uint32) KeyName {
	for k, v := range l {
		if v == position {
			return k
		}
	}
	return ""
}

// Halo75 represents Halo 75 keyboard template
var Halo75 = Template{
	KeyCapsLock:       3,
	KeyLCtrl:          5,
	KeyLShift:         4,
	KeyLAlt:           11,
	KeyLMeta:          17,
	KeyRCtrl:          65,
	KeyRShift:         82,
	KeyRMeta:          53,
	KeyFn:             59,
	KeyIns:            90,
	KeyHome:           91,
	KeyEnd:            92,
	KeyPgUp:           93,
	KeyPgDn:           94,
	KeyEnter:          81,
	KeyTab:            2,
	KeySpace:          35,
	KeyBackspace:      79,
	KeyEsc:            147,
	KeyDel:            84,
	KeyGrave:          1,
	KeyNum1:           164,
	KeyNum2:           165,
	KeyNum3:           166,
	KeyNum4:           167,
	KeyNum5:           31,
	KeyNum6:           37,
	KeyNum7:           43,
	KeyNum8:           49,
	KeyNum9:           55,
	KeyNum0:           61,
	KeyA:              9,
	KeyB:              169,
	KeyC:              162,
	KeyD:              21,
	KeyE:              20,
	KeyF:              176,
	KeyG:              145,
	KeyH:              168,
	KeyI:              50,
	KeyJ:              45,
	KeyK:              51,
	KeyL:              57,
	KeyM:              46,
	KeyN:              170,
	KeyO:              56,
	KeyP:              62,
	KeyQ:              8,
	KeyR:              26,
	KeyS:              15,
	KeyT:              32,
	KeyU:              44,
	KeyV:              163,
	KeyW:              14,
	KeyX:              161,
	KeyY:              38,
	KeyZ:              10,
	KeySemicolon:      63,
	KeyMinus:          174,
	KeyEqual:          175,
	KeyQuote:          69,
	KeyLBracket:       178,
	KeyRBracket:       179,
	KeyBackslash:      177,
	KeyFwdslash:       173,
	KeyComma:          171,
	KeyPeriod:         172,
	KeyScreenshot:     78,
	KeyUp:             148,
	KeyDown:           149,
	KeyLeft:           150,
	KeyRight:          151,
	KeyFnUp:           197,
	KeyFnDown:         196,
	KeyFnLeft:         198,
	KeyFnRight:        199,
	KeyF1:             132,
	KeyF2:             133,
	KeyF3:             134,
	KeyF4:             135,
	KeyF5:             136,
	KeyF6:             137,
	KeyF7:             138,
	KeyF8:             139,
	KeyF9:             140,
	KeyF10:            141,
	KeyF11:            142,
	KeyF12:            143,
	KeyBrightnessDown: 180,
	KeyBrightnessUp:   181,
	KeyMissionControl: 182,
	KeyLaunchpad:      183,
	KeyVoiceCommand:   184,
	KeySpotlight:      185,
	KeyRewind:         186,
	KeyPlayPause:      187,
	KeyForward:        188,
	KeyMute:           189,
	KeyVolumeDown:     190,
	KeyVolumeUp:       191,
}

// Halo65 represents Halo 65 keyboard template
var Halo65 = Template{
	KeyCapsLock:       3,
	KeyLCtrl:          5,
	KeyLShift:         4,
	KeyLAlt:           11,
	KeyLMeta:          17,
	KeyRCtrl:          65,
	KeyRShift:         82,
	KeyRMeta:          53,
	KeyFn:             59,
	KeyHome:           90,
	KeyEnd:            94,
	KeyPgUp:           92,
	KeyPgDn:           93,
	KeyEnter:          81,
	KeyTab:            2,
	KeySpace:          35,
	KeyBackspace:      79,
	KeyEsc:            0,
	KeyNum1:           164,
	KeyNum2:           165,
	KeyNum3:           166,
	KeyNum4:           167,
	KeyNum5:           168,
	KeyNum6:           169,
	KeyNum7:           170,
	KeyNum8:           171,
	KeyNum9:           172,
	KeyNum0:           173,
	KenFNNum1:         6,
	KenFNNum2:         12,
	KenFNNum3:         18,
	KenFNNum4:         24,
	KenFNNum5:         30,
	KenFNNum6:         36,
	KenFNNum7:         42,
	KenFNNum8:         48,
	KenFNNum9:         54,
	KenFNNum0:         60,
	KeyFNMinus:        66,
	KeyFNEqual:        72,
	KeyA:              154,
	KeyB:              136,
	KeyC:              162,
	KeyD:              21,
	KeyE:              159,
	KeyF:              176,
	KeyG:              145,
	KeyH:              137,
	KeyI:              50,
	KeyJ:              45,
	KeyK:              51,
	KeyL:              57,
	KeyM:              46,
	KeyN:              138,
	KeyO:              56,
	KeyP:              62,
	KeyQ:              157,
	KeyR:              160,
	KeyS:              153,
	KeyT:              32,
	KeyU:              44,
	KeyV:              163,
	KeyW:              152,
	KeyX:              161,
	KeyY:              38,
	KeyZ:              10,
	KeySemicolon:      63,
	KeyMinus:          174,
	KeyEqual:          175,
	KeyQuote:          69,
	KeyLBracket:       178,
	KeyRBracket:       179,
	KeyBackslash:      177,
	KeyFwdslash:       135,
	KeyComma:          133,
	KeyPeriod:         134,
	KeyUp:             148,
	KeyDown:           149,
	KeyLeft:           150,
	KeyRight:          151,
	KeyFnUp:           197,
	KeyFnDown:         196,
	KeyFnLeft:         198,
	KeyFnRight:        199,
	KeyBrightnessDown: 180,
	KeyBrightnessUp:   181,
	KeyMissionControl: 182,
	KeyLaunchpad:      183,
	KeyVoiceCommand:   184,
	KeySpotlight:      185,
	KeyRewind:         186,
	KeyPlayPause:      187,
	KeyForward:        188,
	KeyMute:           189,
	KeyVolumeDown:     190,
	KeyVolumeUp:       191,
}

// Templates contains all keyboard templates
var templates = map[device.Model]Template{
	device.Halo75: Halo75,
	device.Halo65: Halo65,
}

// GetTemplate returns template by model
func GetTemplate(name device.Model) *Template {
	if t, ok := templates[name]; ok {
		return &t
	}
	return nil
}
